### ISSUE TITLE
Allow post/comment bodies to be formatted with markdown

### ISSUE THREAD

**Issue by chrispittman** [longhornopen/chatter#15]
...in addition to the WYSIWYG editor tools.  Will probably need to add a 'Preview' tool to see the formatted markdown.  Maybe this should wait until after editing of bodies (#12)

**Comment by clauswilke** [comment]
Thanks for considering. An implementation similar to what GitHub offers would be ideal. I would also suggest to use the same markdown flavor, so that tools that automatically create content for GitHub work with Chatter also.

One such tool that I use literally every day can be seen here: https://reprex.tidyverse.org/articles/articles/magic-reprex.html

**Comment by chrispittman** [comment]
Hey there, @clauswilke

We're currently using Quill as our text editor.  There's a markdown-editing plugin for it at:
    [https://cloverhearts.github.io/quilljs-markdown/](https://cloverhearts.github.io/quilljs-markdown/)
On that page, there's a list of the Markdown syntax it supports out-of-the-box, which seems to be the same as Github's Markdown flavor (unless I'm missing something).  There's also a playground on that page where you can try out the editor.

If you have time in the next week or two, try playing around with that playground and see what you think of the editing experience.  I think it'll work fine for you, but I'd like to give you a chance to try it out and comment before we commit.

**Comment by clauswilke** [comment]
It's great to have some markdown editing available, but unfortunately this system is too limited to be of much practical use.

Things that don't seem to be working:
- Code highlighting (and even more importantly, it doesn't consume the code indicating the chosen highlighting type, so it shows up in the output)
- Images
- HTML tags such as `<sup>`

As a consequence, markdown input that should look like this:

![Screen Shot 2021-06-14 at 5 04 47 PM](https://user-images.githubusercontent.com/4210929/121965566-d628f780-cd32-11eb-9339-acdb724e5020.png)

comes out like this:

![Screen Shot 2021-06-14 at 5 04 35 PM](https://user-images.githubusercontent.com/4210929/121965600-e214b980-cd32-11eb-91da-b41f6f8ec49c.png)

**Comment by chrispittman** [comment]
@clauswilke Hmm.  Can you run a few of your Markdown samples through the [Toast UI editor](https://ui.toast.com/tui-editor) playground, and let me know how it works for you?  (There's a WYSIWYG/Markdown toggle in the lower right of the editor, which you may have to toggle over to 'Markdown'.)

**Comment by clauswilke** [comment]
Toast works great. Everything looks right.

**Comment by chrispittman** [comment]
Cool.  There's a couple of things about Toast UI that I still have to look into before committing to it, but if it works, we'll switch our editor over to it instead.
