### ISSUE TITLE
Ability to tag messages

### ISSUE THREAD

**Issue by dpassovoy** [longhornopen/chatter#17]
Ability to tag messages (e.g., #extra_credit, #exam, etc.)

**Comment by chrispittman** [comment]
Does 'messages' here mean 'posts' (the things on the left - the beginnings of comment threads)?  Or does 'messages' mean 'comments'?  If the former, is this the same thing as #19 ?

**Comment by dpassovoy** [comment]
Hi, Chris.

In my world, ‘posts’ and ‘comments’ are iterations of the same thing.  Whether someone posts a message or comments on someone else’s message, practically speaking it’s the same.

To your specific question, I don’t think tags (#) are the same as ‘type of post’.  Tags should be unlimited—e.g., #homework, #extra_credit—or it might signify an action—e.g., #pin (which would ‘pin’ the post to the top section so it’s always visible; whereas, type of post indicates how program (i.e., Chatter) operates—e.g., ‘announcement’ might just allow the author to enter the post, but a ‘question’ might signify/require a response in order to be completed.  (See Piazza for examples of both.)

Dennis Passovoy | Lecturer | Sam Walton Fellow in Free Enterprise | Management Department | Appointment<https://calendly.com/dennis-passovoy>
The University of Texas at Austin | McCombs School of Business | 512-426-1961 | Website<http://www.mccombs.utexas.edu/> | GSB 5.124G
Impact Fellow | The Impact Factory | Dell Medical School & LBJ School of Public Affairs

Texas McCombs BBA Community Values<https://my.mccombs.utexas.edu/My/BBA/Community-Values>: OUR RESPONSIBILITY | OUR COMMUNITY | OUR GROWTH | OUR BEST

From: Chris Pittman ***@***.***>
Reply-To: longhornopen/chatter ***@***.***>
Date: Tuesday, May 4, 2021 at 8:03 AM
To: longhornopen/chatter ***@***.***>
Cc: Dennis Passovoy ***@***.***>, Author ***@***.***>
Subject: Re: [longhornopen/chatter] Ability to tag messages (#17)


Does 'messages' here mean 'posts' (the things on the left - the beginnings of comment threads)? Or does 'messages' mean 'comments'? If the former, is this the same thing as #19<https://github.com/longhornopen/chatter/issues/19> ?

**Comment by chrispittman** [comment]
You're describing two separate types of tags here, I think.

The second type - the type that implies some kind of action to be taken on the backend - seems to be one of two things in your examples:
1) tags that duplicate a control already in the UI (#pin -> the "Pin" button; #announcement -> the "Lock" button)
2) tags that feed into a part of the backend that doesn't exist yet (e.g. tags that control when a post is 'completed' or 'graded', which are concepts that don't exist in Chatter at the moment), but which we'll probably handle in the same way - via an explicit UI control rather than an implicit tag.

The first type - freeform tags that describe the content of a post to humans - seems to be the same thing as #19 , so I'm going to close this issue in favor of that one.

**Comment by dpassovoy** [comment]
Chris, 

You're right about issue #1 -- 'tag' in that context does imply action (e.g., "#pin").  But don't you think they should 'pin' to the **top** of the "ALL" list of posts so users are drawn to them (maybe with a delineator after the bunch of them before you list the others)?

But the other issue -- #2 -- is meant to help segregate posts from one another.  In my classes, I allow students to use this kind of tool (Chatter) to post general discussions, but also to post  extra credit qualifying posts.  If they can add a tag to those posts, I could filter or sort them out of the others accordingly.  I guess I can do that by using the search feature that already exists.  (Correct me if I'm wrong.).

**Comment by chrispittman** [comment]
Feel free to open a new issue ("Pinned posts should be at the top of the 'All' posts list", or something to that effect) if that's the behavior you want.  I'd want to track that as a separate request for clarity, because it doesn't really have anything to do with _how_ a post gets pinned.

I've been assuming that your request in issue #19 includes the ability to filter posts by tag somehow, but you can post additional commentary over that issue if there's more you want to say about it.

**Comment by chrispittman** [comment]
Rough preview of the UI for editing tags...

In the Settings panel, teachers will be able to edit the list of tags for their class, with the defaults shown here.

![Screenshot from 2021-07-21 15-45-17](https://user-images.githubusercontent.com/918414/126558206-30eb2a65-cc52-4a69-b3d0-e987eb950b18.png)

Editing an existing tag, or creating a new one, will bring up this UI for changing the tag name, color, and whether students are allowed to post using this tag or not:

![Screenshot from 2021-07-21 15-45-47](https://user-images.githubusercontent.com/918414/126558399-adf56c7c-dfea-405e-9d5f-8e3477319f7a.png)

Still need to work out what it looks like to tag a post or to search by tags, but this is a sneak peek of what I'm thinking right now.  Comments welcomed!

**Comment by dpassovoy** [comment]
Generally, this looks good to me.  A couple thoughts, though:

  1.  To delete a tag/post type, why not just have an “X” on the “Edit” button?  Seems less ‘real estate’ and more intuitive to me.
  2.  I assume there is the ability to search posts based on the tags they possess.
  3.  If I’m understanding what I see correctly, tags can be applied by anyone unless the tag is checked as “Teacher Only”.  I like that.

Dennis Passovoy | Lecturer | Sam Walton Fellow in Free Enterprise | Management Department | Appointment<https://calendly.com/dennis-passovoy>
The University of Texas at Austin | McCombs School of Business | 512-426-1961 | Website<http://www.mccombs.utexas.edu/> | GSB 5.124G
Impact Fellow | The Impact Factory | Dell Medical School & LBJ School of Public Affairs

Texas McCombs BBA Community Values<https://my.mccombs.utexas.edu/My/BBA/Community-Values>: OUR RESPONSIBILITY | OUR COMMUNITY | OUR GROWTH | OUR BEST

From: Chris Pittman ***@***.***>
Reply-To: longhornopen/chatter ***@***.***>
Date: Wednesday, July 21, 2021 at 3:53 PM
To: longhornopen/chatter ***@***.***>
Cc: Dennis Passovoy ***@***.***>, Author ***@***.***>
Subject: Re: [longhornopen/chatter] Ability to tag messages (#17)


Rough preview of the UI for editing tags...

In the Settings panel, teachers will be able to edit the list of tags for their class, with the defaults shown here.

[Screenshot from 2021-07-21 15-45-17]<https://user-images.githubusercontent.com/918414/126558206-30eb2a65-cc52-4a69-b3d0-e987eb950b18.png>

Editing an existing tag, or creating a new one, will bring up this UI for changing the tag name, color, and whether students are allowed to post using this tag or not:

[Screenshot from 2021-07-21 15-45-47]<https://user-images.githubusercontent.com/918414/126558399-adf56c7c-dfea-405e-9d5f-8e3477319f7a.png>

Still need to work out what it looks like to tag a post or to search by tags, but this is a sneak peek of what I'm thinking right now. Comments welcomed!
