### ISSUE TITLE
Ability to code posts as different types

### ISSUE THREAD

**Issue by dpassovoy** [longhornopen/chatter#19]
Ability to code posts as different types of posts – announcements, questions, posts, etc.

**Comment by chrispittman** [comment]
Rough preview of the UI for editing tags...

In the Settings panel, teachers will be able to edit the list of tags for their class, with the defaults shown here.

![Screenshot from 2021-07-21 15-45-17](https://user-images.githubusercontent.com/918414/126558206-30eb2a65-cc52-4a69-b3d0-e987eb950b18.png)

Editing an existing tag, or creating a new one, will bring up this UI for changing the tag name, color, and whether students are allowed to post using this tag or not:

![Screenshot from 2021-07-21 15-45-47](https://user-images.githubusercontent.com/918414/126558399-adf56c7c-dfea-405e-9d5f-8e3477319f7a.png)

Still need to work out what it looks like to tag a post or to search by tags, but this is a sneak peek of what I'm thinking right now.  Comments welcomed!

**Comment by chrispittman** [comment]
Tagged posts now show their tag next to the title:

![Screenshot from 2021-07-23 15-36-15](https://user-images.githubusercontent.com/918414/126838766-619c943f-fe8c-43fc-aa54-e8a4175d1b7b.png)

The 'plus-search' icon opens an advanced search mode, where you can specify the tag you're searching for.  Possibly additional search types (search by poster, maybe?) here in the future.

![Screenshot from 2021-07-23 15-37-13](https://user-images.githubusercontent.com/918414/126838943-8826ba55-41e6-4dcf-b5a8-3e1fd8a21341.png)
