### ISSUE TITLE
Allow users to post files

### ISSUE THREAD

**Issue by marlagilliland** [longhornopen/chatter#22]
Consider allowing the ability to post files (on posts and comments) through an admin setting to be toggled on or off for the board.

**Comment by chrispittman** [comment]
What does 'files' mean here?  Are you wanting to upload images?  Sound?  Video?  PDFs?  Any arbitrary file?

**Comment by marlagilliland** [comment]
I believe this specific request was about sharing out work in progress on math problems, which might include images, word docs, pdfs.

**Comment by bapfeld1** [comment]
Just a quick update: we've received a few more requests for "the ability to post pictures" in Posts, Replies, and Comments.

**Comment by chrispittman** [comment]
The new WYSIWYG editor allows for including images and linking to files hosted externally.
