### ISSUE TITLE
Tally and display the number of users who have viewed a post

### ISSUE THREAD

**Issue by marlagilliland** [longhornopen/chatter#29]

**Comment by chrispittman** [comment]
I'm assuming this is just an 'Are students paying attention?' gauge?  Or is there something else you want out of this view count?

**Comment by marlagilliland** [comment]
The general idea was the 'who is paying attention' gauge for the prof as noted -- and in a small way to add to the sense of the classroom community.  "I'm reading this (whenever that may be), and so have 300 of my classmates".
