### ISSUE TITLE
Migrate all PINned posts to the top of the display-all list

### ISSUE THREAD

**Issue by dpassovoy** [longhornopen/chatter#35]
When the author of a post PINs it, it should display at the top of the LIST ALL list, along with all the other PINned posts.  There should be a delineator of some sort at the end of the PINned posts (e.g., a bold line), if possible, that indicates the list below them includes the rest of the regular posts.

**Comment by bapfeld1** [comment]
Before we move forward on this, I'd like to know more about why this feature would be a benefit to multiple courses or instructors. My concern is that by removing the Pinned post list at the top of the post navigation bar, and only having Pinned posts before all other posts on the List All list, this will discourage students from scrolling down past the (possibly numerous) Pinned posts and seeing and responding to posts that weren't pinned but are still meaningful / useful. If the main motivator is that students are potentially not looking at the Pinned post list itself, I'd like to be sure that is a widespread issue before implementing this change.

**Comment by dpassovoy** [comment]
That's a good point.  

In my case, I can tell you I only pin 2-3 posts per course.  They include info such as office hours and a reminder to do the extra credit posts.  If students have to click on a separate tab to see them, they are much less likely to see these posts or to be reminded of them a few weeks into the semester.

I would suggest, however, that you survey other instructors and see if this modification would work for them or not.

**Comment by chrispittman** [comment]
Part of the problem is that we don't have a lot of real-world usage yet, so there aren't that many instructors and students to survey right now.  Leaving this one open for the moment; we'll get UT Austin (and maybe some other institutions) to run a survey at the end of the fall semester and see if we can make a data-driven decision here.  Tagging this as work for the fall-2021 Project so that we don't forget.
