### ISSUE TITLE
Add 'time' to the setting for when the class/Chatter ends

### ISSUE THREAD

**Issue by dpassovoy** [longhornopen/chatter#39]
Having the ability to add a time would be a great advantage.  Personally, I use discussions (Chatter, in this case) for students to post extra credit thoughts relating to the material in the course.  The deadline is when they walk into class on the last day of classes.

**Comment by dpassovoy** [comment]
I just saw that you (Chris) added this right after I posted.  Thanks!

**Comment by chrispittman** [comment]
Agreed, this'd be really handy.

**Comment by chrispittman** [comment]
I think we posted the same thing within ten seconds of each other.  Let's go with yours.  Reopening.

**Comment by chrispittman** [comment]
Added as part of Vue2->3 conversion in 49c46d6d
