### ISSUE TITLE
Editing a post or reply results in an error

### ISSUE THREAD

**Issue by dpassovoy** [longhornopen/chatter#41]
An attempt to edit a post or reply results in a "Something went wrong" error and no way to correct the post.

**Comment by chrispittman** [comment]
It's possible you were just logged out due to inactivity.  We do need a more-specific error message in that case.

**Comment by dpassovoy** [comment]
Nope – not a timeout situation.

I logged out of Canvas, logged back in, selected my course, navigated to Chatter, selected the post, hit the ellipsis, selected edit, hit save – all in the span of about 60 seconds – and received the following error:

[Graphical user interface, text, application  Description automatically generated]

Dennis Passovoy | Lecturer | Sam Walton Fellow in Free Enterprise | Management Department | Appointment<https://calendly.com/dennis-passovoy>
The University of Texas at Austin | McCombs School of Business | 512-426-1961 | Website<http://www.mccombs.utexas.edu/> | GSB 5.124G
Impact Fellow | The Impact Factory | Dell Medical School & LBJ School of Public Affairs

Texas McCombs BBA Community Values<https://my.mccombs.utexas.edu/My/BBA/Community-Values>: OUR RESPONSIBILITY | OUR COMMUNITY | OUR GROWTH | OUR BEST

From: Chris Pittman ***@***.***>
Reply-To: longhornopen/chatter ***@***.***>
Date: Friday, July 23, 2021 at 1:12 PM
To: longhornopen/chatter ***@***.***>
Cc: Dennis Passovoy ***@***.***>, Author ***@***.***>
Subject: Re: [longhornopen/chatter] Editing a post or reply results in an error (#41)


It's possible you were just logged out due to inactivity. We do need a more-specific error message in that case.

**Comment by chrispittman** [comment]
I'm seeing a lot of errors related to somebody trying to edit a post that they didn't write.  We've since fixed this by removing the 'Edit' option for such posts, but that version hasn't been released to UT Austin yet.

**Comment by dpassovoy** [comment]
I wrote the reply I was trying to edit. Someone else wrote to post.

Dennis Passovoy | Lecturer | Sam Walton Fellow in Free Enterprise | Management Department | Appointment<https://calendly.com/dennis-passovoy>
The University of Texas at Austin | McCombs School of Business | 512-426-1961 | Website<http://www.mccombs.utexas.edu/> | GSB 5.124G
Impact Fellow | The Impact Factory | Dell Medical School & LBJ School of Public Affairs

Texas McCombs BBA Community Values<https://my.mccombs.utexas.edu/My/BBA/Community-Values>: OUR RESPONSIBILITY | OUR COMMUNITY | OUR GROWTH | OUR BEST

On Jul 23, 2021, at 5:21 PM, Chris Pittman ***@***.***> wrote:

﻿

I'm seeing a lot of errors related to somebody trying to edit a post that they didn't write. We've since fixed this by removing the 'Edit' option for such posts, but that version hasn't been released to UT Austin yet.
