### ISSUE TITLE
Highlight response from Instructor

### ISSUE THREAD

**Issue by jalapic** [longhornopen/chatter#53]
When responding to a discussion post, it would be helpful if the instructor or TAs response was highlighted somehow (either bolding the name of the instructor, or changing the appearance of the post).  In longer discussion posts, students may want to find the instructor's response quickly.

**Comment by chrispittman** [comment]
![Screenshot from 2021-09-02 15-19-58](https://user-images.githubusercontent.com/918414/131913141-2691a2e3-97f9-4012-a566-6bcb2fbfba55.png)

May need to tweak the display a bit here, but something like this will be in this weekend's release.

**Comment by jalapic** [comment]
Awesome! thanks.
