### ISSUE TITLE
Math/LaTex markup not working?

### ISSUE THREAD

**Issue by jmottame** [longhornopen/chatter#65]
Tried adding LaTex markup to a post last night (5/8) but didn't seem to be working. I followed the instructions (encompass markup in $$latex ... $$), but not sure if I'm missing something else, like maybe I need to have a library pre-loaded on my machine?

**Comment by chrispittman** [comment]
You shouldn't need anything installed to make latex markup work.

We currently only allow latex to be displayed as a block (on a line of its own), not inline.  Make sure you're entering it at the beginning of a new line.  It'll become syntax-colored if you've got it right, like in this screenshot.

![Screenshot 2022-05-09 100515](https://user-images.githubusercontent.com/918414/167440059-79a793a5-fbaa-414d-8490-5809155649c8.png)

Let us know whether that works or not.

**Comment by jmottame** [comment]
Thanks Chris. That's how I have it setup, but the result shows up without markup. Screenshots below.

![image](https://user-images.githubusercontent.com/105221313/169319186-56ab6c85-d2bd-4128-b384-75ace1f5257b.png)

![image](https://user-images.githubusercontent.com/105221313/169319257-80277641-f10e-40cb-a904-187e45230dac.png)

**Comment by chrispittman** [comment]
Hmm.  This may be something that depends on which browser you're using.  Can you share:
1) Which browser (name + version)
2) Which Operating System (Mac, Windows, ...)
...that you're seeing this in?

**Comment by jmottame** [comment]
Using Chrome Version 101.0.4951.64, and macOs 12.3.1

**Comment by chrispittman** [comment]
Thanks.  Looking into it in the next few days.

**Comment by chrispittman** [comment]
I think this is fixed now.  If you're still seeing math-markup problems, please let us know.

**Comment by jmottame** [comment]
Can confirm that the markup shows now. Thanks!
